# Site information
site_name: "语文探源"
site_url: https://hantang.github.io/cntextbook/
site_author: hantang
site_description: "Chinese textbooks"
copyright: Copyright &copy; 2025 Hantang

# Repository
repo_name: cntextbook
repo_url: https://github.com/hantang/cntextbook/
# edit_uri: tree/main

theme:
  name: material
  custom_dir: overrides
  favicon: static/favicon.ico
  logo: static/logo.png
  language: "zh"

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.footer
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tooltips
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.progress

extra_css:
  - https://cdn.jsdelivr.net/npm/heti@0.9.6/umd/heti.min.css
  # - https://cdn.jsdelivr.net/npm/diff2html/bundles/css/diff2html.min.css
  - static/css/extra.css

extra_javascript:
  # - https://cdnjs.cloudflare.com/ajax/libs/Han/3.2.7/han.min.js
  - https://cdn.jsdelivr.net/npm/heti@0.9.6/umd/heti-addon.min.js
  # - https://cdn.jsdelivr.net/npm/diff2html/bundles/js/diff2html.min.js
  - static/js/remove-space.js
  # - https://unpkg.com/heti/umd/heti-addon.min.js

plugins:
  - search:
      lang:
        - en
        - zh
      separator: '[\s\-,:!=\[\]()"/\u200b]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - meta
  - mkdocs-embed-pdf
  - callouts
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  # - nl2br
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.snippets
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 首页: index.md
  - 补充资料:
    - 课程标准:
      - 课程标准/index.md
      - 义务教育:
          - 课程标准/义务教育/index.md
          - 课程标准/义务教育/前言.md
          - 课程标准/义务教育/课程性质.md
          - 课程标准/义务教育/课程理念.md
          - 课程标准/义务教育/课程目标.md
          - 课程标准/义务教育/课程内容.md
          - 课程标准/义务教育/学业质量.md
          - 课程标准/义务教育/课程实施.md
          - 附录:
              - 课程标准/义务教育/附录/index.md
              - 课程标准/义务教育/附录/优秀诗文背诵推荐篇目.md
              - 课程标准/义务教育/附录/关于课内外读物的建议.md
              - 课程标准/义务教育/附录/关于语法修辞知识的说明.md
              - 课程标准/义务教育/附录/识字、写字教学基本字表.md
              - 课程标准/义务教育/附录/义务教育语文课程常用字表.md
      - 普通高中:
          - 课程标准/普通高中/index.md
          - 课程标准/普通高中/前言.md
          - 课程标准/普通高中/课程性质与基本理念.md
          - 课程标准/普通高中/学科核心素养与课程目标.md
          - 课程标准/普通高中/课程结构.md
          - 课程标准/普通高中/课程内容.md
          - 课程标准/普通高中/学业质量.md
          - 课程标准/普通高中/实施建议.md
          - 附录:
              - 课程标准/普通高中/附录/index.md
              - 课程标准/普通高中/附录/古诗文背诵推荐篇目.md
              - 课程标准/普通高中/附录/关于课内外读物的建议.md
    - "🔗 中小学生阅读指导目录": https://fantribe.github.io/books/edu/
    - "🔗 中小学优秀古诗文篇目": https://fantribe.github.io/books/edu/classic/
